# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src

# Install dependencies and package
RUN pip install --no-cache-dir .

# Expose if needed (MCP uses stdio)

# Default command to start the MCP server
CMD ["flyworks-mcp"]
